server:
  port: 8080

spring:
  application:
    name: productservice

#  eureka:
#    client:
#      service-url:
#        defaultZone: http://localhost:8761/eureka/

  data:
    mongodb:
#      uri: mongodb://localhost:27017/javatechiemongodb
      host: localhost
      port: 27017
      database: javatechiemongodb
      auto-index-creation: true

  redis:
    host: localhost
    port: 6379

#  cache:
#    type: redis